/*++
    WebifyVDD - Virtual Display Driver for Webify

    Creates virtual monitors for multi-user Win32 app streaming.
    Each monitor exposes frames via shared memory so webify-server
    can read them without PrintWindow/EnumWindows hacks.

    Based on Microsoft IddSampleDriver.
    Environment: User Mode, UMDF
--*/

#include "Driver.h"
// WPP tracing disabled for CMake build — .tmh generated by WPP preprocessor
// #include "Driver.tmh"

using namespace std;
using namespace Webify;
using namespace Microsoft::WRL;

#pragma region Config

// Number of virtual monitors to create at startup
static constexpr DWORD MONITOR_COUNT = 4;

// Default mode: 1024x768@60 (matches webify-server default)
static const struct {
    DWORD Width;
    DWORD Height;
    DWORD VSync;
} s_DefaultModes[] = {
    { 1920, 1080, 60 },
    { 1024,  768, 60 },
    {  800,  600, 60 },
};

#pragma endregion

#pragma region Helpers

static inline void FillSignalInfo(DISPLAYCONFIG_VIDEO_SIGNAL_INFO& Mode,
                                   DWORD Width, DWORD Height, DWORD VSync, bool bMonitorMode)
{
    Mode.totalSize.cx = Mode.activeSize.cx = Width;
    Mode.totalSize.cy = Mode.activeSize.cy = Height;
    Mode.AdditionalSignalInfo.vSyncFreqDivider = bMonitorMode ? 0 : 1;
    Mode.AdditionalSignalInfo.videoStandard = 255;
    Mode.vSyncFreq.Numerator = VSync;
    Mode.vSyncFreq.Denominator = 1;
    Mode.hSyncFreq.Numerator = VSync * Height;
    Mode.hSyncFreq.Denominator = 1;
    Mode.scanLineOrdering = DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE;
    Mode.pixelRate = ((UINT64)VSync) * ((UINT64)Width) * ((UINT64)Height);
}

static IDDCX_MONITOR_MODE CreateIddCxMonitorMode(DWORD Width, DWORD Height, DWORD VSync,
    IDDCX_MONITOR_MODE_ORIGIN Origin = IDDCX_MONITOR_MODE_ORIGIN_DRIVER)
{
    IDDCX_MONITOR_MODE Mode = {};
    Mode.Size = sizeof(Mode);
    Mode.Origin = Origin;
    FillSignalInfo(Mode.MonitorVideoSignalInfo, Width, Height, VSync, true);
    return Mode;
}

static IDDCX_TARGET_MODE CreateIddCxTargetMode(DWORD Width, DWORD Height, DWORD VSync)
{
    IDDCX_TARGET_MODE Mode = {};
    Mode.Size = sizeof(Mode);
    FillSignalInfo(Mode.TargetVideoSignalInfo.targetVideoSignalInfo, Width, Height, VSync, false);
    return Mode;
}

#pragma endregion

#pragma region WDF/IddCx Callbacks

extern "C" DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD WebifyDeviceAdd;
EVT_WDF_DEVICE_D0_ENTRY WebifyDeviceD0Entry;
EVT_IDD_CX_ADAPTER_INIT_FINISHED WebifyAdapterInitFinished;
EVT_IDD_CX_ADAPTER_COMMIT_MODES WebifyAdapterCommitModes;
EVT_IDD_CX_PARSE_MONITOR_DESCRIPTION WebifyParseMonitorDescription;
EVT_IDD_CX_MONITOR_GET_DEFAULT_DESCRIPTION_MODES WebifyMonitorGetDefaultModes;
EVT_IDD_CX_MONITOR_QUERY_TARGET_MODES WebifyMonitorQueryModes;
EVT_IDD_CX_MONITOR_ASSIGN_SWAPCHAIN WebifyMonitorAssignSwapChain;
EVT_IDD_CX_MONITOR_UNASSIGN_SWAPCHAIN WebifyMonitorUnassignSwapChain;

struct IndirectDeviceContextWrapper {
    IndirectDeviceContext* pContext;
    void Cleanup() { delete pContext; pContext = nullptr; }
};

struct IndirectMonitorContextWrapper {
    IndirectMonitorContext* pContext;
    void Cleanup() { delete pContext; pContext = nullptr; }
};

WDF_DECLARE_CONTEXT_TYPE(IndirectDeviceContextWrapper);
WDF_DECLARE_CONTEXT_TYPE(IndirectMonitorContextWrapper);

#pragma endregion

extern "C" BOOL WINAPI DllMain(HINSTANCE, UINT, LPVOID) { return TRUE; }

extern "C" NTSTATUS DriverEntry(PDRIVER_OBJECT pDriverObject, PUNICODE_STRING pRegistryPath)
{
    WDF_DRIVER_CONFIG Config;
    WDF_OBJECT_ATTRIBUTES Attributes;
    WDF_OBJECT_ATTRIBUTES_INIT(&Attributes);
    WDF_DRIVER_CONFIG_INIT(&Config, WebifyDeviceAdd);
    return WdfDriverCreate(pDriverObject, pRegistryPath, &Attributes, &Config, WDF_NO_HANDLE);
}

NTSTATUS WebifyDeviceAdd(WDFDRIVER Driver, PWDFDEVICE_INIT pDeviceInit)
{
    UNREFERENCED_PARAMETER(Driver);

    WDF_PNPPOWER_EVENT_CALLBACKS PnpPowerCallbacks;
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&PnpPowerCallbacks);
    PnpPowerCallbacks.EvtDeviceD0Entry = WebifyDeviceD0Entry;
    WdfDeviceInitSetPnpPowerEventCallbacks(pDeviceInit, &PnpPowerCallbacks);

    IDD_CX_CLIENT_CONFIG IddConfig;
    IDD_CX_CLIENT_CONFIG_INIT(&IddConfig);
    IddConfig.EvtIddCxAdapterInitFinished = WebifyAdapterInitFinished;
    IddConfig.EvtIddCxParseMonitorDescription = WebifyParseMonitorDescription;
    IddConfig.EvtIddCxMonitorGetDefaultDescriptionModes = WebifyMonitorGetDefaultModes;
    IddConfig.EvtIddCxMonitorQueryTargetModes = WebifyMonitorQueryModes;
    IddConfig.EvtIddCxAdapterCommitModes = WebifyAdapterCommitModes;
    IddConfig.EvtIddCxMonitorAssignSwapChain = WebifyMonitorAssignSwapChain;
    IddConfig.EvtIddCxMonitorUnassignSwapChain = WebifyMonitorUnassignSwapChain;

    NTSTATUS Status = IddCxDeviceInitConfig(pDeviceInit, &IddConfig);
    if (!NT_SUCCESS(Status)) return Status;

    WDF_OBJECT_ATTRIBUTES Attr;
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&Attr, IndirectDeviceContextWrapper);
    Attr.EvtCleanupCallback = [](WDFOBJECT Object) {
        auto* pContext = WdfObjectGet_IndirectDeviceContextWrapper(Object);
        if (pContext) pContext->Cleanup();
    };

    WDFDEVICE Device = nullptr;
    Status = WdfDeviceCreate(&pDeviceInit, &Attr, &Device);
    if (!NT_SUCCESS(Status)) return Status;

    Status = IddCxDeviceInitialize(Device);

    auto* pContext = WdfObjectGet_IndirectDeviceContextWrapper(Device);
    pContext->pContext = new IndirectDeviceContext(Device);

    return Status;
}

NTSTATUS WebifyDeviceD0Entry(WDFDEVICE Device, WDF_POWER_DEVICE_STATE PreviousState)
{
    UNREFERENCED_PARAMETER(PreviousState);
    auto* pContext = WdfObjectGet_IndirectDeviceContextWrapper(Device);
    pContext->pContext->InitAdapter();
    return STATUS_SUCCESS;
}

#pragma region Direct3DDevice

Direct3DDevice::Direct3DDevice(LUID AdapterLuid) : AdapterLuid(AdapterLuid) {}
Direct3DDevice::Direct3DDevice() { AdapterLuid = LUID{}; }

HRESULT Direct3DDevice::Init()
{
    HRESULT hr = CreateDXGIFactory2(0, IID_PPV_ARGS(&DxgiFactory));
    if (FAILED(hr)) return hr;

    hr = DxgiFactory->EnumAdapterByLuid(AdapterLuid, IID_PPV_ARGS(&Adapter));
    if (FAILED(hr)) return hr;

    hr = D3D11CreateDevice(Adapter.Get(), D3D_DRIVER_TYPE_UNKNOWN, nullptr,
                            D3D11_CREATE_DEVICE_BGRA_SUPPORT, nullptr, 0,
                            D3D11_SDK_VERSION, &Device, nullptr, &DeviceContext);
    return hr;
}

#pragma endregion

#pragma region SwapChainProcessor

SwapChainProcessor::SwapChainProcessor(IDDCX_SWAPCHAIN hSwapChain,
    shared_ptr<Direct3DDevice> Device, HANDLE NewFrameEvent, UINT MonitorIndex)
    : m_hSwapChain(hSwapChain), m_Device(Device), m_hAvailableBufferEvent(NewFrameEvent),
      m_MonitorIndex(MonitorIndex), m_hSharedMem(nullptr), m_pSharedMem(nullptr)
{
    m_hTerminateEvent.Attach(CreateEvent(nullptr, FALSE, FALSE, nullptr));

    // Create shared memory for this monitor: "WebifyVDD_Monitor_0", "WebifyVDD_Monitor_1", etc.
    wchar_t shmName[64];
    swprintf_s(shmName, L"Global\\WebifyVDD_Monitor_%u", MonitorIndex);

    m_hSharedMem = CreateFileMappingW(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE,
                                       0, (DWORD)SHARED_MEM_SIZE, shmName);
    if (m_hSharedMem) {
        m_pSharedMem = (SharedFrameHeader*)MapViewOfFile(m_hSharedMem, FILE_MAP_ALL_ACCESS,
                                                          0, 0, SHARED_MEM_SIZE);
        if (m_pSharedMem) {
            memset(m_pSharedMem, 0, sizeof(SharedFrameHeader));
            m_pSharedMem->magic = SHARED_MAGIC;
        }
    }

    m_hThread.Attach(CreateThread(nullptr, 0, RunThread, this, 0, nullptr));
}

SwapChainProcessor::~SwapChainProcessor()
{
    SetEvent(m_hTerminateEvent.Get());
    if (m_hThread.Get()) {
        WaitForSingleObject(m_hThread.Get(), INFINITE);
    }
    if (m_pSharedMem) UnmapViewOfFile(m_pSharedMem);
    if (m_hSharedMem) CloseHandle(m_hSharedMem);
}

DWORD CALLBACK SwapChainProcessor::RunThread(LPVOID Argument)
{
    reinterpret_cast<SwapChainProcessor*>(Argument)->Run();
    return 0;
}

void SwapChainProcessor::Run()
{
    DWORD AvTask = 0;
    HANDLE AvTaskHandle = AvSetMmThreadCharacteristicsW(L"Distribution", &AvTask);

    RunCore();

    WdfObjectDelete((WDFOBJECT)m_hSwapChain);
    m_hSwapChain = nullptr;

    if (AvTaskHandle) AvRevertMmThreadCharacteristics(AvTaskHandle);
}

void SwapChainProcessor::RunCore()
{
    ComPtr<IDXGIDevice> DxgiDevice;
    HRESULT hr = m_Device->Device.As(&DxgiDevice);
    if (FAILED(hr)) return;

    IDARG_IN_SWAPCHAINSETDEVICE SetDevice = {};
    SetDevice.pDevice = DxgiDevice.Get();
    hr = IddCxSwapChainSetDevice(m_hSwapChain, &SetDevice);
    if (FAILED(hr)) return;

    for (;;)
    {
        IDARG_OUT_RELEASEANDACQUIREBUFFER Buffer = {};
        hr = IddCxSwapChainReleaseAndAcquireBuffer(m_hSwapChain, &Buffer);

        if (hr == E_PENDING)
        {
            HANDLE WaitHandles[] = { m_hAvailableBufferEvent, m_hTerminateEvent.Get() };
            DWORD WaitResult = WaitForMultipleObjects(ARRAYSIZE(WaitHandles), WaitHandles, FALSE, 16);
            if (WaitResult == WAIT_OBJECT_0 || WaitResult == WAIT_TIMEOUT)
                continue;
            else
                break;
        }
        else if (SUCCEEDED(hr))
        {
            ComPtr<IDXGIResource> AcquiredBuffer;
            AcquiredBuffer.Attach(Buffer.MetaData.pSurface);

            // Copy frame to shared memory for webify-server to read
            if (m_pSharedMem)
            {
                ComPtr<ID3D11Texture2D> Texture;
                hr = AcquiredBuffer.As(&Texture);
                if (SUCCEEDED(hr))
                {
                    D3D11_TEXTURE2D_DESC desc;
                    Texture->GetDesc(&desc);

                    UINT w = min(desc.Width, (UINT)MAX_WIDTH);
                    UINT h = min(desc.Height, (UINT)MAX_HEIGHT);

                    // Create or recreate staging texture if needed
                    if (!m_StagingTexture)
                    {
                        D3D11_TEXTURE2D_DESC stagingDesc = {};
                        stagingDesc.Width = w;
                        stagingDesc.Height = h;
                        stagingDesc.MipLevels = 1;
                        stagingDesc.ArraySize = 1;
                        stagingDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
                        stagingDesc.SampleDesc.Count = 1;
                        stagingDesc.Usage = D3D11_USAGE_STAGING;
                        stagingDesc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;

                        m_Device->Device->CreateTexture2D(&stagingDesc, nullptr, &m_StagingTexture);
                    }

                    if (m_StagingTexture)
                    {
                        // GPU copy to staging texture
                        m_Device->DeviceContext->CopyResource(m_StagingTexture.Get(), Texture.Get());

                        // Map staging texture to CPU memory
                        D3D11_MAPPED_SUBRESOURCE mapped;
                        hr = m_Device->DeviceContext->Map(m_StagingTexture.Get(), 0,
                                                          D3D11_MAP_READ, 0, &mapped);
                        if (SUCCEEDED(hr))
                        {
                            // Write frame to shared memory
                            BYTE* dst = (BYTE*)m_pSharedMem + sizeof(SharedFrameHeader);
                            BYTE* src = (BYTE*)mapped.pData;
                            UINT copyStride = w * 4;

                            for (UINT row = 0; row < h; row++)
                            {
                                memcpy(dst + row * copyStride, src + row * mapped.RowPitch, copyStride);
                            }

                            m_pSharedMem->width = w;
                            m_pSharedMem->height = h;
                            m_pSharedMem->stride = copyStride;
                            m_pSharedMem->frame_number++;
                            m_pSharedMem->ready = 1;

                            m_Device->DeviceContext->Unmap(m_StagingTexture.Get(), 0);
                        }
                    }
                }
            }

            AcquiredBuffer.Reset();

            hr = IddCxSwapChainFinishedProcessingFrame(m_hSwapChain);
            if (FAILED(hr)) break;
        }
        else
        {
            break;
        }
    }
}

#pragma endregion

#pragma region IndirectDeviceContext

IndirectDeviceContext::IndirectDeviceContext(WDFDEVICE WdfDevice) : m_WdfDevice(WdfDevice)
{
    m_Adapter = {};
}

IndirectDeviceContext::~IndirectDeviceContext() {}

void IndirectDeviceContext::InitAdapter()
{
    IDDCX_ADAPTER_CAPS AdapterCaps = {};
    AdapterCaps.Size = sizeof(AdapterCaps);
    AdapterCaps.MaxMonitorsSupported = MONITOR_COUNT;
    AdapterCaps.EndPointDiagnostics.Size = sizeof(AdapterCaps.EndPointDiagnostics);
    AdapterCaps.EndPointDiagnostics.GammaSupport = IDDCX_FEATURE_IMPLEMENTATION_NONE;
    AdapterCaps.EndPointDiagnostics.TransmissionType = IDDCX_TRANSMISSION_TYPE_WIRED_OTHER;
    AdapterCaps.EndPointDiagnostics.pEndPointFriendlyName = L"Webify Virtual Display";
    AdapterCaps.EndPointDiagnostics.pEndPointManufacturerName = L"Webify";
    AdapterCaps.EndPointDiagnostics.pEndPointModelName = L"WebifyVDD";

    IDDCX_ENDPOINT_VERSION Version = {};
    Version.Size = sizeof(Version);
    Version.MajorVer = 1;
    AdapterCaps.EndPointDiagnostics.pFirmwareVersion = &Version;
    AdapterCaps.EndPointDiagnostics.pHardwareVersion = &Version;

    WDF_OBJECT_ATTRIBUTES Attr;
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&Attr, IndirectDeviceContextWrapper);

    IDARG_IN_ADAPTER_INIT AdapterInit = {};
    AdapterInit.WdfDevice = m_WdfDevice;
    AdapterInit.pCaps = &AdapterCaps;
    AdapterInit.ObjectAttributes = &Attr;

    IDARG_OUT_ADAPTER_INIT AdapterInitOut;
    NTSTATUS Status = IddCxAdapterInitAsync(&AdapterInit, &AdapterInitOut);

    if (NT_SUCCESS(Status))
    {
        m_Adapter = AdapterInitOut.AdapterObject;
        auto* pContext = WdfObjectGet_IndirectDeviceContextWrapper(AdapterInitOut.AdapterObject);
        pContext->pContext = this;
    }
}

void IndirectDeviceContext::FinishInit(UINT ConnectorIndex)
{
    WDF_OBJECT_ATTRIBUTES Attr;
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&Attr, IndirectMonitorContextWrapper);

    IDDCX_MONITOR_INFO MonitorInfo = {};
    MonitorInfo.Size = sizeof(MonitorInfo);
    MonitorInfo.MonitorType = DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI;
    MonitorInfo.ConnectorIndex = ConnectorIndex;

    // No EDID — use default modes
    MonitorInfo.MonitorDescription.Size = sizeof(MonitorInfo.MonitorDescription);
    MonitorInfo.MonitorDescription.Type = IDDCX_MONITOR_DESCRIPTION_TYPE_EDID;
    MonitorInfo.MonitorDescription.DataSize = 0;
    MonitorInfo.MonitorDescription.pData = nullptr;

    CoCreateGuid(&MonitorInfo.MonitorContainerId);

    IDARG_IN_MONITORCREATE MonitorCreate = {};
    MonitorCreate.ObjectAttributes = &Attr;
    MonitorCreate.pMonitorInfo = &MonitorInfo;

    IDARG_OUT_MONITORCREATE MonitorCreateOut;
    NTSTATUS Status = IddCxMonitorCreate(m_Adapter, &MonitorCreate, &MonitorCreateOut);
    if (NT_SUCCESS(Status))
    {
        auto* pWrapper = WdfObjectGet_IndirectMonitorContextWrapper(MonitorCreateOut.MonitorObject);
        pWrapper->pContext = new IndirectMonitorContext(MonitorCreateOut.MonitorObject, ConnectorIndex);

        IDARG_OUT_MONITORARRIVAL ArrivalOut;
        IddCxMonitorArrival(MonitorCreateOut.MonitorObject, &ArrivalOut);
    }
}

IndirectMonitorContext::IndirectMonitorContext(IDDCX_MONITOR Monitor, UINT MonitorIndex)
    : m_Monitor(Monitor), m_MonitorIndex(MonitorIndex)
{
}

IndirectMonitorContext::~IndirectMonitorContext()
{
    m_ProcessingThread.reset();
}

void IndirectMonitorContext::AssignSwapChain(IDDCX_SWAPCHAIN SwapChain, LUID RenderAdapter, HANDLE NewFrameEvent)
{
    m_ProcessingThread.reset();

    auto Device = make_shared<Direct3DDevice>(RenderAdapter);
    if (FAILED(Device->Init()))
    {
        WdfObjectDelete(SwapChain);
    }
    else
    {
        m_ProcessingThread.reset(new SwapChainProcessor(SwapChain, Device, NewFrameEvent, m_MonitorIndex));
    }
}

void IndirectMonitorContext::UnassignSwapChain()
{
    m_ProcessingThread.reset();
}

#pragma endregion

#pragma region DDI Callbacks

NTSTATUS WebifyAdapterInitFinished(IDDCX_ADAPTER AdapterObject, const IDARG_IN_ADAPTER_INIT_FINISHED* pInArgs)
{
    auto* pWrapper = WdfObjectGet_IndirectDeviceContextWrapper(AdapterObject);
    if (NT_SUCCESS(pInArgs->AdapterInitStatus))
    {
        for (DWORD i = 0; i < MONITOR_COUNT; i++)
        {
            pWrapper->pContext->FinishInit(i);
        }
    }
    return STATUS_SUCCESS;
}

NTSTATUS WebifyAdapterCommitModes(IDDCX_ADAPTER AdapterObject, const IDARG_IN_COMMITMODES* pInArgs)
{
    UNREFERENCED_PARAMETER(AdapterObject);
    UNREFERENCED_PARAMETER(pInArgs);
    return STATUS_SUCCESS;
}

NTSTATUS WebifyParseMonitorDescription(const IDARG_IN_PARSEMONITORDESCRIPTION* pInArgs,
                                        IDARG_OUT_PARSEMONITORDESCRIPTION* pOutArgs)
{
    // We use edid-less monitors, so this shouldn't be called
    UNREFERENCED_PARAMETER(pInArgs);
    pOutArgs->MonitorModeBufferOutputCount = 0;
    return STATUS_SUCCESS;
}

NTSTATUS WebifyMonitorGetDefaultModes(IDDCX_MONITOR MonitorObject,
    const IDARG_IN_GETDEFAULTDESCRIPTIONMODES* pInArgs,
    IDARG_OUT_GETDEFAULTDESCRIPTIONMODES* pOutArgs)
{
    UNREFERENCED_PARAMETER(MonitorObject);

    if (pInArgs->DefaultMonitorModeBufferInputCount == 0)
    {
        pOutArgs->DefaultMonitorModeBufferOutputCount = ARRAYSIZE(s_DefaultModes);
    }
    else
    {
        for (DWORD i = 0; i < ARRAYSIZE(s_DefaultModes); i++)
        {
            pInArgs->pDefaultMonitorModes[i] = CreateIddCxMonitorMode(
                s_DefaultModes[i].Width, s_DefaultModes[i].Height, s_DefaultModes[i].VSync,
                IDDCX_MONITOR_MODE_ORIGIN_DRIVER);
        }
        pOutArgs->DefaultMonitorModeBufferOutputCount = ARRAYSIZE(s_DefaultModes);
        pOutArgs->PreferredMonitorModeIdx = 0;
    }
    return STATUS_SUCCESS;
}

NTSTATUS WebifyMonitorQueryModes(IDDCX_MONITOR MonitorObject,
    const IDARG_IN_QUERYTARGETMODES* pInArgs, IDARG_OUT_QUERYTARGETMODES* pOutArgs)
{
    UNREFERENCED_PARAMETER(MonitorObject);

    vector<IDDCX_TARGET_MODE> TargetModes;
    TargetModes.push_back(CreateIddCxTargetMode(1920, 1080, 60));
    TargetModes.push_back(CreateIddCxTargetMode(1024, 768, 60));
    TargetModes.push_back(CreateIddCxTargetMode(800, 600, 60));

    pOutArgs->TargetModeBufferOutputCount = (UINT)TargetModes.size();

    if (pInArgs->TargetModeBufferInputCount >= TargetModes.size())
    {
        copy(TargetModes.begin(), TargetModes.end(), pInArgs->pTargetModes);
    }

    return STATUS_SUCCESS;
}

NTSTATUS WebifyMonitorAssignSwapChain(IDDCX_MONITOR MonitorObject, const IDARG_IN_SETSWAPCHAIN* pInArgs)
{
    auto* pWrapper = WdfObjectGet_IndirectMonitorContextWrapper(MonitorObject);
    pWrapper->pContext->AssignSwapChain(pInArgs->hSwapChain, pInArgs->RenderAdapterLuid, pInArgs->hNextSurfaceAvailable);
    return STATUS_SUCCESS;
}

NTSTATUS WebifyMonitorUnassignSwapChain(IDDCX_MONITOR MonitorObject)
{
    auto* pWrapper = WdfObjectGet_IndirectMonitorContextWrapper(MonitorObject);
    pWrapper->pContext->UnassignSwapChain();
    return STATUS_SUCCESS;
}

#pragma endregion
